### ISSUE TITLE
You should add this Fumo to the game I think it would really make the game just so much better

### ISSUE THREAD

**Issue by Jolene-sama** [NafeeJ/Fumo-Bounce#3]
![0BC00854-E503-4D2D-B5FD-046FF1D1E430](https://user-images.githubusercontent.com/33842041/89747058-fb9e0280-da8a-11ea-811a-d8d4af4ebd40.jpeg)

**Comment by NafeeJ** [comment]
![nocat](https://user-images.githubusercontent.com/33550260/89748084-808b1b00-da8f-11ea-8302-9fd0dc835a21.gif)
